### ISSUE TITLE
The migrate script does not update the version in settings.yaml

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1006]
**Describe the bug:** (a clear and concise description of what the bug is)

**To Reproduce**

1. Go to define new version in values.changes.yaml
2. build otomi-core image
3. perform an upgrade by updating the version via otomi-console
4. Observe Drone pipeline, the bootstrap step and see that the migrate scripts sees new version
```
2023-01-12T13:05:15.350Z otomi:cmd:migrate:migrate:log Migration changes: [
  {
    "kind": "E",
    "path": [
      "version"
    ],
    "lhs": 5,
    "rhs": 6
  }
]
```
5. Observe that the version has not been updates in the values repo (at gitea)
![image.png](https://images.zenhubusercontent.com/5e81a8d81dea46667ed31838/b171bc93-99a3-4464-8895-4e39b946c5d6)

**Expected behavior:** (a clear and concise description of what you expected to happen)
The version is updated, so pipeline does not perform migration with each run.

**Comment by Morriz** [comment]
> 1. Go to define new version in values.changes.yaml

That is not the source of truth, just a list of operations to run up to the version as specified in the values. That schema version is initially set during bootstrap, and updated by `otomi migrate`. 

So, in order to check that ther is really an issue, please check:

1. the version in the container: `.values/env/settings.yaml`
2. The version in the values. 

If there is no mismatch, otomi migrate will not run anything, and therefor will not increment anything either. I will close this issue now, but feel free to create a feature request or enhancement if the current way can be improved.

I do think we should set the version via our schema templating abilities: `x-template: 'print "5"'`. (`x-template` does not yet exist, but `x-secret` does, which could share the same functionality.)
