### ISSUE TITLE
Unexpected switch to the latest tag 

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1067]
**Describe the bug:** (a clear and concise description of what the bug is)

By installing Otomi from helm chart a user may not specify `otomi.version` parameter. 
Otomi installs versions specified in the `Chart.yaml` file. However this versions does not end up in the values repo.
Thus, in the Otomi console there is no Otomi versions and by editing any other setting the default `latest` values is added.
 
**To Reproduce**

1. Ensure that otomi.version is not set in the values repo
2. In otomi console, go to settings and edit any input field except  the `version` and click submit
3. Click `Deploy changes` 
4. Observe that in the values repo `latest` tag is set at `otomi.version` in the settings.yaml file.

**Expected behavior:** (a clear and concise description of what you expected to happen)
If Otomi is installed from chart and there is not explicit `otomi.version` provided then merge `.Values` with the 
value from ` .Chart.AppVersion`

**Screenshots:** (if applicable, add screenshots to help explain your problem)

**Cluster(s):**

- Cloud: [e.g. aws]
- Cluster: [e.g. demo]

**Versions:** (seen in console's `/settings`)

- Core Versionv: 0.24.0

**Comment by ElderMatt** [comment]
I did find this in the Otomi bash script, so it looks like expected behaviour! @j-zimnowoda What do you want me to do with this?

![image.png](https://images.zenhubusercontent.com/642ac41a10e7f6615835d8ef/baf24b51-320c-4e5e-8245-6b6d6b7c428d)

**Comment by j-zimnowoda** [comment]
@ElderMatt I think that the `chart/otomi/templates/values-secrets.yaml` file needs to be modified, so the values that are bootstrapped always contain `otomi.version`.

**Comment by j-zimnowoda** [comment]
@ElderMatt I think that the `chart/otomi/templates/values-secrets.yaml` file needs to be modified, so the values that are bootstrapped always contain `otomi.version`.

**Comment by Ani1357** [comment]
- created feature branch with changes to the  otomi chart template values-secrets.yaml
- while testing I noticed drone authentication was not working with the following error.
![Screenshot 2023-05-01 at 17.39.44.png](https://images.zenhubusercontent.com/642ac5c36fe3e326cc94305b/d779b17a-928a-47f5-ba37-a684e8411a8f)
- going through drone logs I found this error:
![Screenshot 2023-05-01 at 17.44.39.png](https://images.zenhubusercontent.com/642ac5c36fe3e326cc94305b/7a893706-8bba-428c-bf15-e7ddb00f62ac)
- tested otomi core v0.20.3 and it works fine, it seems the issue is in current master
