### ISSUE TITLE
Support k8s 1.25

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1129]
**Is your feature request related to a problem? 

**Describe the solution you'd like**
**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features
you've considered.

**Additional context** Add any other context or screenshots about the feature request here.

**Comment by Ani1357** [comment]
Working on current [branch from Cas](https://github.com/redkubes/otomi-core/tree/cas/feat/k8s-1-25-upgrade).

- Deployed otomi on k8s v1.25 using the minimal otomi profile: Succes ✅
- Deployed the same branch using the full profile : Failed ❌
  - Logs show that kubeapps helm installation failed. Looking at the pod logs its showed this error 
![Screenshot 2023-06-26 at 13.31.07.png](https://images.zenhubusercontent.com/642ac5c36fe3e326cc94305b/19a06711-a48f-4d91-b914-387d946e90bc)
- Deployed  a new cluster with the minimal profile and enabling harbor before kubeapps manually(to see if we have a racing condition): Failed ❌
  - This time the reason seems not related to otomi. The kubeapps-kubeops image used by our current kubeapps chart does not exist.
- Deployed  a new cluster with the full profile but disabling only kubeapps: Succes ✅
  - Run a smoke test of the different apps in the otomi-console:
    - Kiali is giving a 503 when accessing the url but we were expecting that. 
    - Jeager is also giving a 503(not sure if it has some other dependencies)
    - Alert manager shows "no healthy upstream"
    - All other apps seem to work fine

**Comment by j-zimnowoda** [comment]
Great report. Did you manage to solve any of failing apps ?
