### ISSUE TITLE
Upgrade cert-manager to 1.11

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1177]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem
is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like** A clear and concise description of what you want to happen.

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features
you've considered.

**Additional context** Add any other context or screenshots about the feature request here.

**Comment by Ani1357** [comment]
As per the [upgrade documentation](https://cert-manager.io/docs/installation/upgrading/), it should be a smooth minor version bump but in practice it is not. Trying to simply upgrade the  helm chart throws errors related  deployments not being patched. This is because the label selectors of the deployment are different and a patch operation can not be completed(since its immutable filed).
Tried adding an upgrade script to uninstall the helm release before installing the new chart version but this results in the deletion of the current certificates which is not idea. 
The final solution is to include an update script which will delete only the deployments before the helm upgrade,  this way the old certificates can be used also.
