### ISSUE TITLE
loki sometimes does not show logs

### ISSUE THREAD

**Issue by Morriz** [redkubes/otomi-core#171]
**Describe the bug** A clear and concise description of what the bug is.

Loki sometimes does not show logs, while kubectl shows them fine. 

**To Reproduce** Steps to reproduce the behavior.

I needed to see harbor logs but could not see anything in loki with these labels:
```
{component="registry"}
```
(Even though they were suggested!)
But this worked:
```
kh logs -l component=registry -c registry -f
```

**Expected behavior** A clear and concise description of what you expected to happen.

Logs to show for those labels

**Additional context** Add any other context about the problem here.

It was detected onprem, so we have to check demo after new harbor deployment as well, so we can investigate with same setup, and if it happens there too, we have to deduce wether it is related to harbor. If it was only onprem, we have to find out why (disk usage?).

**Comment by svatwork** [comment]
Attempting to reproduce the problem on the demo cluster.

```bash
➜  ~ kh logs -l component=registry -c registry -f
127.0.0.1 - - [08/Apr/2021:12:00:54 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.19+"
127.0.0.1 - - [08/Apr/2021:12:01:00 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
127.0.0.1 - - [08/Apr/2021:12:01:02 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.19+"
127.0.0.1 - - [08/Apr/2021:12:01:04 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.19+"
127.0.0.1 - - [08/Apr/2021:12:01:10 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
127.0.0.1 - - [08/Apr/2021:12:01:12 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.19+"
127.0.0.1 - - [08/Apr/2021:12:01:14 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.19+"
127.0.0.1 - - [08/Apr/2021:12:01:20 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
127.0.0.1 - - [08/Apr/2021:12:01:22 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.19+"
127.0.0.1 - - [08/Apr/2021:12:01:24 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.19+"
```

etc.

```bash
➜  ~ kubectl -n monitoring port-forward loki-0 :3100

Forwarding from 127.0.0.1:36009 -> 3100
Forwarding from [::1]:36009 -> 3100
```

```bash
➜  ~ export LOKI_ADDR=http://localhost:36009
➜  ~ logcli query '{component="registry"}'

http://localhost:36009/loki/api/v1/query_range?direction=BACKWARD&end=xxxx&limit=30&query=%7Bcomponent%3D%22registry%22%7D&start=yyyy
Query failed: Error response from server: no org id
```

I've tried to look up the `tenant_id` or `X-OrgId` from somewhere but couldn't find it, could you please provide some more details on this bug?

**Comment by svatwork** [comment]
```bash
➜  ~ logcli --org-id="1" query '{component="registry"}'
http://localhost:36009/loki/api/v1/query_range?direction=BACKWARD&end=xxxx&limit=30&query=%7Bcomponent%3D%22registry%22%7D&start=yyyy
➜  ~ logcli --org-id="2" query '{component="registry"}'
http://localhost:36009/loki/api/v1/query_range?direction=BACKWARD&end=xxxx&limit=30&query=%7Bcomponent%3D%22registry%22%7D&start=yyyy
```

**Comment by Morriz** [comment]
Please don't ever access services via proxy

**Comment by svatwork** [comment]
> Please don't ever access services via proxy

Alright, but you probably understand I cannot learn anything from this statement.

**Comment by svatwork** [comment]
Had a conversation with @Morriz today.

Just want to report on the author's comment about the limit if it's to anyone help...

- https://github.com/grafana/loki/issues/1917#issuecomment-634577346

"You can set the value to 0 so the limit will be disabled. But you should be really careful when you do this. You might end up crashing Loki or Grafana might become unresponsive if you try to load huge number of log lines. This was the reason we added this limit so that we don't crash loki.

Having said all the above points, it's good to have a limit on how many log lines you can query. To decide the exact number of the limit you would have to do some monitoring on your system to see how many log lines you are adding in your 14 day period. In Promtail we expose read_lines_total metric, you can watch this metric to see rate of logs being written over a period of time. Be sure to adjust your memory on Loki instance if you are querying huge number of log lines."

**Comment by Morriz** [comment]
not reproducible after learning about the quirks of operating loki ;p
