### ISSUE TITLE
Unable to login to harbor dashboard

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#185]
**Describe the bug**
Unable to login to harbor dashboard after Keycloak redeployment (most probably)

**To Reproduce**
Steps to reproduce:
1. Open harbor dashboard in web browser: https://harbor.demo.eks.otomi.cloud/
2. You are redirected to login with IDP
3. Login as otomi.admin@redkubes.net
4. Redirected to harbor login dashboard 
5. Click: `LOGIN VIA OIDC PROVIDER`
6. Logout from harbor and logout from https://otomi.dev.onprem.otomi.cloud
7. Remove and redeploy keycloak
8. Repeat steps 1-4
9. Observe dialog `Set OIDC Username`
10. Click `Save` button
11. Observe error `Conflict, the user with same username or email has been onboarded.`

**Expected behavior**

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e81a8d81dea46667ed31838/cc81ff02-0ef7-4077-88c0-61d294e5ff57)

**Additional context**
Cluster: https://otomi.dev.onprem.otomi.cloud

**Comment by Morriz** [comment]
Me and @j-zimnowoda just talked through possible solutions and we came up with these scenarios:

1. keycloak can be manipulated to use the IDPs sub as-is (requires work from keycloak, but it might not be possible because of referential integrity on the sub which is used as id consistently)
2. harbor can be manipulated to work with another claim than 'sub' and we map IDP sub to another claim in keycloak. Looking at their code they just expect a varchar(255) and have no index on it so it would be less work than option 1.

Option 2 is the shortest path here imo, as intuitively I think the keycloak devs won't support our request to screw up their database model.

**Comment by Morriz** [comment]
I have asked for this feature with harbor: https://github.com/goharbor/harbor/issues/13674

**Comment by j-zimnowoda** [comment]
@Morriz I am wondering if we can create a keycloak mapper for `sub` claim.

Then `sub` would be rewritten from original token?

**Comment by j-zimnowoda** [comment]
@Morriz I am wondering if we can create a keycloak mapper for `sub` claim.

Then `sub` would be rewritten from original token.

I am just not sure about possible collisions if keycloak is an IdP broker for many IdPs.

**Comment by Morriz** [comment]
I think that is a good idea, yes. We can provide configurations for multiple IDPs, so I don't see a problem there.

**Comment by Morriz** [comment]
@j-zimnowoda this needs prio as demos are failing again. Can you inplement that mapper?

**Comment by j-zimnowoda** [comment]
I have created the mapper nut it does not seem to take into effect, as I see that keycloak still assign sub for a new users instead of reusing the original one.

![image.png](https://images.zenhubusercontent.com/5e81a8d81dea46667ed31838/45e950ba-ae6d-44a6-8211-5d05400dab33)

![image.png](https://images.zenhubusercontent.com/5e81a8d81dea46667ed31838/d434d73f-1821-4974-8b98-05bc9763769e)

**Comment by j-zimnowoda** [comment]
I also was thinking to use script mappers but this option seems to be deprecated.
```
​-Dkeycloak.profile.feature.upload_scripts=enable
```

**Comment by j-zimnowoda** [comment]
We will create a mapper **oidc to sub.**


![image.png](https://images.zenhubusercontent.com/5e81a8d81dea46667ed31838/d01cac6e-53ef-411d-9982-5fa36693adb5)
