### ISSUE TITLE
Enhance OPA policies

### ISSUE THREAD

**Issue by Morriz** [redkubes/otomi-core#19]
We want our opa policies to also limit access to the following resources:
- istio stuff
- ResourceQuota
- ?

**Comment by rawc0der** [comment]
We should start refactoring all the policies to a common `.rego` language syntax, since the Konstraint library is going to support `input.parameters` as part of the `core` definitions.  

PR that started all the mess here - https://github.com/plexsystems/konstraint/pull/80
Nice to see the community reacting so quickly

**Comment by j-zimnowoda** [comment]
> Nice to see the community reacting so quickly
Indeed that is really encouraging

**Comment by Morriz** [comment]
Awesome!
