### ISSUE TITLE
Bootstrap only essential values

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#381]
**Is your feature request related to a problem?**

When I bootstrap otomi values there are many configuration parameters that are optional.
In particular there are hardcoded container image versions for the `otomi-api` and `otomi-console` apps (the latest tag)
However, given `otomi-core` version are released with specific version of `otomi-api` and `otomi-console` not latest one.

@bartboshuizen thank you for pointing this out.

**Describe the solution you'd like**
Bootstrap only those values that are essential for user to fill in.
Do not bootstrap image `tag` and `pullPollicy`.

**Additional context**
See `.demo/env/charts/*`

**Comment by Morriz** [comment]
The demo files are problematic as they serve 2 functions:

1. contain as much as possible configuration to cover code paths
2. demo files for bootstrap phase

Now, given 1 you can deduce that we want those settings in there, and working. So please don't think that we should remove them there (not now at least).

Taking 2 into account, it is also beneficial that the examples show what is possible.

So I am closing this for now, as I don't see any action related to this observation.

**Comment by j-zimnowoda** [comment]
Well, the solution is simple.
Have values for bootstrap and for test for coverage and used both of them while running validation tests.

Please do not ignore our reports. I see you are closing a lot of them, without really consulting it with the team.

**Comment by Morriz** [comment]
I just think that when we bootstrap a new user with values, those should be present. We should not adopt a mindset that avoids yaml configuration because "it looks like a lot of stuff". Instead we should focus on installing those values with minimal configuration changes. After flattening that could be as easy as installing a chart. See https://github.com/redkubes/otomi-core/issues/374.

And I am not making those decisions lightly, I just don't always feel like overly explaining higher order principles. 

If you want to make a useful extraction from this issue, then please create a story to get better coverage:
- it should have values for each cloud
- ??

But like I said, demo values should show what is useful. I believe the above example about otomi-api and otomi-console NOT being in the demo values is the wrong direction. IMO they SHOULD be in there as it shows that it is easy to test out new versions of those components without getting guarantees that they will. When components can be upgraded without tests breaking, and after observing them for a while, we can decide to backport those versions in core.

**Comment by j-zimnowoda** [comment]
If I buy a new car, I just want to press `start` button and have a pleasant first journey. 
With time and need, I will discover all the parameters.
Maybe, I even tune the engine but only if my first impression is positive.

**Comment by Morriz** [comment]
Maybe you are right, but we should provide demo values imo. That is what they are: demo values. We can provide docs that say you can just toss them away and start fresh. We should bootstrap them next to `env` in `envDemo` I think. Then we have to maintain 2 sets of values: demo and clean. Clean setup can just contain the files.

**Comment by Morriz** [comment]
good idea!
