### ISSUE TITLE
Missing -p|--profile argument

### ISSUE THREAD

**Issue by vfarcic** [redkubes/otomi-core#450]
**Describe the bug:** (a clear and concise description of what the bug is)

Getting the following error:

```
Installing artifacts from otomi/core:master
Stored YAML schema at: /Users/vfarcic/code/otomi-demo/.vscode/values-schema.yaml
Missing -p|--profile argument.
```

**To Reproduce**

```bash
# Create a GKE cluster

mkdir otomi-demo

cd otomi-demo

export PROFILE=google

docker container run --rm \
    --env ENV_DIR=$PWD \
    --volume $PWD:$PWD \
    otomi/core:latest \
    bin/bootstrap.sh $PROFILE
```

**Expected behavior:** (a clear and concise description of what you expected to happen)

There should be no error.

As a bonus, the script should verify whether all the requirements are fulfilled before it starts "doing stuff".

**Cluster(s):**

- Cloud: GCP
- Cluster: GKE

**Comment by Morriz** [comment]
Hey, tnx for trying the installation routine. We are almost ready with a chart installer, and might have broken master. Hope to update the docs next week when we deliver the chart install.

**Comment by Morriz** [comment]
For now it should be possible to just add the `-p` before `$PROFILE` (as the error mentions). You can try:
```
docker container run --rm \
    --env ENV_DIR=$PWD \
    --volume $PWD:$PWD \
    otomi/core:latest \
    bin/bootstrap.sh -p $PROFILE
```
But like I said we are about to publish a chart, which will have an extensive `values.yaml` file with a `values.schema.json` file to verify the input. We will also provide a `values-minimal.yaml` file for quick deployment, because we understand the size of all the available options can be daunting ;)

**Comment by Morriz** [comment]
fixed in master to not use profiles any more...docs updated as well
