### ISSUE TITLE
Go templating: source the readFile from absolute path

### ISSUE THREAD

**Issue by svatwork** [redkubes/otomi-core#468]
At the moment a `readFile` function is executed in our Go templating to source the `ENV_DIR`. This assumes that the `ENV_DIR` is mounted in `${stack_dir}/env`. Relative paths limit us for obvious reasons. Can we replace it with a command like (please assume pseudo-syntax):

```go
{{- $v := (readFile(fmt.Sprintf("%s/env/cluster.yaml", os.getEnv("ENV_DIR")) | fromYaml) }}
```

E.g. for cluster.yaml.

**Comment by Morriz** [comment]
The location of $ENV_DIR (`${stack_dir}/env`) is a necessity for the container and drone to run helmfile. So please don't waste time investigating wether it's possible to move it somewhere else...

**Comment by Dunky13** [comment]
I don't know enough about drone for this. But the container mounts `${stack_dir}/env` as well as `$ENV_DIR`. So $ENV_DIR would be available in the container, thus that doesn't matter.
Like I said, don't know about the impact on drone. But it would seem like a more solid solution to use a absolute path, instead of relative paths.

**Comment by svatwork** [comment]
I don't think @Morriz wants an open conversation about this so I'm not gonna waste my energy on it...

**Comment by Morriz** [comment]
I am not against open conversations, but I can say that I spent quite some time on this, and see no value in revisiting this.
