### ISSUE TITLE
Migration of the values overwrites env/teams/apps.admin.yaml

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#813]
**Describe the bug:** (a clear and concise description of what the bug is)

I noticed that after specifying new change version in `values-changes.yaml` file and running otomi migrate the content of the ` env/teams/apps.admin.yaml` file is overwrite .

**To Reproduce**

1. Specify a new version in `value-changes.yaml` file
e.g. add `- version: 3`
2. Export ENV_DIR to indicate values directory
3. Ensure that content of `$ENV_DIR/env/teams/apps.admin.yaml` has some shortcuts defined:
```
 teamConfig:
     admin:
        apps:
            alertmanager:
                shortcuts: [a]
```
4. From otomi-core dir run `otomi migrate`
5. Observe that the `$ENV_DIR/env/teams/apps.admin.yaml` file  is overwrite with the following content:
```
teamConfig:
    admin:
        apps: []
```

**Expected behavior:** (a clear and concise description of what you expected to happen)
This file is not overwritten if it already exists

**Comment by Morriz** [comment]
This is probably due to the recent omission of reading values from `teams/apps.*` files in [`env.gotmpl:L33`](https://github.com/redkubes/otomi-core/blob/140a8cdf27ec8cbd8c6139a28874e1a8586eb585/helmfile.d/snippets/env.gotmpl#L33) because of conflicts with core app paths. I am not quite clear about why and how that created conflict, but the `teams/apps.*` files only exist for the api+console to hold shortcuts (for now). That is why I thought it would be safe to omit them from core read-in. 

Now, since they are part of te schema, and they should be subject to migrations, we have to re-enable reading in of these files. Any conflicts that arise should then be handled differently...
