### ISSUE TITLE
Consistent and documented permissions of admin

### ISSUE THREAD

**Issue by merll** [redkubes/otomi-core#849]
**Is your feature request related to a problem? Please describe.**

From discussions in #837 and suggested PR #842 there does not seem to be full concensus on
* What `otomi-admin` should have access to.
* What `team-admin` should have access to.
* How multitenancy should impact the access of `team-admin`.

Initially we should define the rationale behind defining access in each app, then assess the current situation in each app, before deciding on the best approach to implement the desired behavior (where necessary).

**Describe the solution you'd like**

The `otomi-admin` account should not be shared among different individuals. Therefore, `otomi-admin` should only be used for the inital login after installation, for setting up individual `team-admin` accounts. This does not necessarily imply that `team-admin` members need universal access to everything inside Otomi, but admins could also be part of multiple teams, e.g. in case they need to help out with secrets administration. However, `team-admin` members need to be able to manage teams and user accounts. `otomi-admin` may have universal access, but access should be strictly audited and not be used in routine activities.

In multitenancy scenarios, teams should obviously only have access to their own secrets. In non-multitenancy-mode, it is reasonable that the access is consistent with other apps. For example, if users can manage another team's apps, that might also require access to their secrets (or at least selected values, see #843).

**Describe alternatives you've considered**

A few examples, since there could be many alternatives:
* Adding `otomi-admin` to the `team-admin` would be the simplest approach to ensure that the former has at least the same access as `team-admin`, potentially more.
* `otomi-admin` could only have access to user and team administration, but nothing else.
* `team-admin` could have access to everything, **except** other teams' secrets, while `otomi-admin` could have universal full access.

**Comment by Morriz** [comment]
Thanks for the elaborate write down @merll. I want to add that we have talked about this extensively with @srodenhuis and @j-zimnowoda and we concluded the following general vision:

- `otomi-admin` has full access to platform configuration only.
- `team-admin` has full access to team resources, except secrets (when also added specifically to a `team-*` they get access to the secrets there)

Because secrets are special and under strict scrutiny, those should only be accessible by those who create/need it, so no blanket access to `team-admin` nor `otomi-admin`
